# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=22.1.2
  - nodejs=16.14.2
  - pip:
      - robotframework-browser==17.1.0
      - rpaframework==24.0.0
rccPostInstall:
  - rfbrowser init
